### ISSUE TITLE
Password?

### ISSUE THREAD

**Issue by michaelaye** [komailo/cookiecutter-python-package#38]
Why does the execution of this cookiecutter require my GitHub password?? No other cookiecutter needs that? Have you been hacked?

**Comment by komailo** [comment]
Let me have a look. My account has not been hacked and I checked the commit history it seems to be all my work.

**Comment by komailo** [comment]
I don't see a password prompt [here](https://github.com/digimach/cookiecutter-python-package/blob/master/cookiecutter.json).
Can you please provide steps to reproduce this?
